apiVersion: apps/v1
kind: Deployment
metadata:
  name: realstate-web
  labels:
    app: realstate-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realstate-web
  template:
    metadata:
      labels:
        app: realstate-web
    spec:
      containers:
      - name: realstate-web
        image: jaylikhare/realstate-web:${{ github.sha }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: estate-config
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: DJANGO_SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: DB_PASSWORD
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
